"""
Django settings for hireflow_main project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from dotenv import load_dotenv
import os

load_dotenv(BASE_DIR / ".env")
FASTAPI_URL = os.getenv("FASTAPI_URL")


SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"


# ALLOWED_HOSTS = [
#     'api.hire-flow.online',
#     'www.hire-flow.online',
#     'hire-flow.online',
#     'localhost',
#     '127.0.0.1',
#     '.svc.cluster.local',
#     '192.168.0.0/16',
#     '10.0.0.0/8',
#     '172.16.0.0/12',

# ]
ALLOWED_HOSTS = ["*"]

CORS_ALLOWED_ORIGINS = [
    "https://www.hire-flow.online",
    "https://hire-flow.online",
    "http://localhost:5173",
]


# CSRF is also strict with HTTPS
CSRF_TRUSTED_ORIGINS = [
    "https://www.hire-flow.online",
    "https://hire-flow.online",
    "http://localhost:5173",
]

APPEND_SLASH = False

SECURE_SSL_REDIRECT = False
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SESSION_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SAMESITE = "None"

SESSION_COOKIE_DOMAIN = ".hire-flow.online"
CSRF_COOKIE_DOMAIN = ".hire-flow.online"

CORS_ALLOW_CREDENTIALS = True
# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cloudinary",
    "apps.accounts",
    "apps.jobs",
    "apps.management",
    "admin_apps.hr_manage",
    "rest_framework",
    "drf_spectacular",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "storages",
    "django_celery_beat",
    "apps.live_chat",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLINT_ID")

REST_FRAMEWORK = {
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "apps.accounts.authentication.CookieJWTAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "daily-job-alerts": {
        "task": "apps.jobs.tasks.send_daily_job_notifications",
        "schedule": crontab(hour=10, minute=30),
    },
    "daily-job-alerts-afternoon": {
        "task": "apps.jobs.tasks.send_daily_job_notifications",
        "schedule": crontab(hour=12, minute=30),
    },
    "daily-job-alerts-evening": {
        "task": "apps.jobs.tasks.send_daily_job_notifications",
        "schedule": crontab(hour=18, minute=30),
    },
}

import ssl

REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = 6379


PROTOCOL = "rediss"


secure_context = ssl.create_default_context()

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                {
                    "address": f"rediss://{REDIS_HOST}:{REDIS_PORT}/0",
                    "ssl_context": secure_context,
                }
            ],
        },
    },
}

CELERY_BROKER_USE_SSL = {"ssl_cert_reqs": ssl.CERT_REQUIRED}
CELERY_REDIS_BACKEND_USE_SSL = {"ssl_cert_reqs": ssl.CERT_REQUIRED}

CELERY_BROKER_URL = f"rediss://{REDIS_HOST}:{REDIS_PORT}/0"


CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.environ.get("CLOUDINARY_CLOUD_NAME"),
    "API_KEY": os.environ.get("CLOUDINARY_API_KEY"),
    "API_SECRET": os.environ.get("CLOUDINARY_API_SECRET"),
    "STATICFILES_MANIFEST_ROOT": None,
}


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}
CELERY_REDIS_BACKEND_USE_SSL = {"ssl_cert_reqs": None}
CELERY_BROKER_USE_SSL = {"ssl_cert_reqs": None}

ACCESS_COOKIE_NAME = "access_token"


REFRESH_COOKIE_NAME = "refresh_token"

SPECTACULAR_SETTINGS = {
    "TITLE": "Smart Recruitment API",
    "DESCRIPTION": "API documentation for HR & Candidate system",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
}

AUTH_USER_MODEL = "accounts.User"


ROOT_URLCONF = "hireflow_main.urls"


# settings.py
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp-relay.brevo.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("BREVO_API_KEY")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hireflow_main.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"
CELERY_ENABLE_UTC = True

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# 2. Where Django "collects" files for the webserver (output)
# This is where your Admin CSS lives!
STATIC_ROOT = BASE_DIR / "staticfiles"

# 3. The URL prefix
STATIC_URL = "/static/"
