version: "3.9"

services:

  # =============================
  # 1️⃣ MAIN DATABASE (Postgres)
  # =============================
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: hireflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - "5432:5432"
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    restart: always
    # FIX: Add this line to resolve the SQLite permission error
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    volumes:
      - dynamodb_data:/data
    ports:
      - "8003:8000"
    networks:
      - internal
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_automation
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - internal

  # =============================
  # 2️⃣ REDIS (Celery broker)
  # =============================
  redis:
    image: redis:7-alpine
    container_name: redis_broker
    restart: always
    networks:
      - internal

  # =============================
  # 3️⃣ MINIO (Object storage)
  # =============================
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - internal

  # =============================
  # 4️⃣ BACKEND DJANGO
  # =============================
  backend:
    container_name: django_backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
      - minio
      - backend_celery_worker
      - backend_celery_beat
    env_file:
      - ./backend/.env
    networks:
      - internal
    ports:
      - "8000:8000"

  # =============================
  # 5️⃣ BACKEND CELERY WORKER
  # =============================
  backend_celery_worker:
    container_name: backend_celery_worker
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A hireflow_main worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - db
    env_file:
      - ./backend/.env
    environment:
      - TZ=Asia/Kolkata
    networks:
      - internal

  # =============================
  # 6️⃣ BACKEND CELERY BEAT
  # =============================
  backend_celery_beat:
    container_name: backend_celery_beat
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A hireflow_main beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - backend_celery_worker
      - redis
      - db
    env_file:
      - ./backend/.env
    environment:
      - TZ=Asia/Kolkata
    networks:
      - internal

  # =============================
  # 7️⃣ CHROMA DB
  # =============================
  chroma:
    image: chromadb/chroma
    container_name: chroma_db
    restart: always
    ports:
      - "8005:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - internal

  # =============================
  # 8️⃣ MONGODB (AI logs)
  # =============================
  mongodb:
    image: mongo:7
    container_name: mongodb_ai_logs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - internal

  # =============================
  # 9️⃣ NGINX API GATEWAY
  # =============================
  nginx:
    image: nginx:latest
    container_name: api_gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - internal

  # =============================
  # 🔟 AI SERVICE (FastAPI)
  # =============================
  ai_service:
    container_name: fastapi_ai_service
    restart: always
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    command: uvicorn app_main.main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./ai_service:/app
    depends_on:
      - chroma
      - mongodb
      - minio
    env_file:
      - ./ai_service/.env
    networks:
      - internal
    ports:
      - "8002:8002"

# =============================
# NETWORK
# =============================
networks:
  internal:

# =============================
# VOLUMES
# =============================
volumes:
  postgres_data:
  minio_data:
  chroma_data:
  mongodb_data:
  dynamodb_data:
  n8n_data: