version: "3.9"

services:

  # =============================
  # 1️⃣ MAIN DATABASE
  # =============================
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: hireflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - "5432:5432"

  # =============================
  # 2️⃣ LIVE CHAT DATABASE
  # =============================
  live_chat_db:
    image: postgres:15
    container_name: live_chat_db
    restart: always
    environment:
      POSTGRES_DB: hireflow_live_db
      POSTGRES_USER: live_chat_user
      POSTGRES_PASSWORD: 12345
    volumes:
      - live_chat_db_data:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - "5433:5432"
  chroma:
    image: chromadb/chroma
    container_name: chroma_db
    restart: always
    ports:
      - "8005:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - internal

  mongodb:
    image: mongo:7
    container_name: mongodb_ai_logs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - internal

  # =============================
  # 3️⃣ REDIS (Broker + Channels)
  # =============================
  redis:
    image: redis:7-alpine
    container_name: redis_broker
    restart: always
    networks:
      - internal

  # =============================
  # 4️⃣ MINIO (Object Storage)
  # =============================
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - internal

  # =============================
  # 5️⃣ MAIN DJANGO BACKEND
  # =============================
  backend:
    container_name: django_backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - minio
    env_file:
      - ./backend/.env
    networks:
      - internal
    ports:
      - "8000:8000"

  # =============================
  # 6️⃣ LIVE CHAT SERVICE
  # =============================
  celery_worker:
    container_name: live_chat_celery
    restart: always
    build:
      context: ./live_services
      dockerfile: Dockerfile
    command: celery -A live_service_main worker --loglevel=info
    volumes:
      - ./live_services:/app
    depends_on:
      - redis
      - live_chat_db
      
    env_file:
      - ./live_services/.env
    networks:
      - internal
  live_chat:
    container_name: django_live_chat
    restart: always
    build:
      context: ./live_services
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./live_services:/app
    depends_on:
      - live_chat_db
      - redis
      - celery_worker
    env_file:
      - ./live_services/.env
    networks:
      - internal


  # =============================
  # 8️⃣ NGINX API GATEWAY
  # =============================
  nginx:
    image: nginx:latest
    container_name: api_gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - live_chat
    networks:
      - internal
  ai_service:
    container_name: fastapi_ai_service
    restart: always
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    command: uvicorn app_main.main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./ai_service:/app
    depends_on:
      - chroma
      - mongodb
    env_file:
      - ./ai_service/.env
    networks:
      - internal
    ports:
      - "8002:8002"

# =============================
# NETWORK
# =============================
networks:
  internal:

# =============================
# VOLUMES
# =============================
volumes:
  postgres_data:
  live_chat_db_data:
  minio_data:
  chroma_data:
  mongodb_data: