# Generated by Django 5.0.6 on 2026-02-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_id',
            field=models.IntegerField(null=True),
        ),
    ]
