# Generated by Django 5.0.6 on 2026-02-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_notification_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
