# Generated by Django 6.0.2 on 2026-02-17 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_number_verified_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(max_length=255)),
                ('company_size', models.CharField(max_length=100)),
                ('headquarters', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hrprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='hrprofile',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='hrprofile',
            name='designation',
        ),
        migrations.AddField(
            model_name='user',
            name='hr_password',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CANDIDATE', 'Candidate'), ('INTERVIEWER', 'Interviewer'), ('ADMIN', 'Admin'), ('HR', 'HR')], max_length=20),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_members', to='accounts.company'),
        ),
    ]
