# Generated by Django 6.0.2 on 2026-02-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_remove_hrprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
