# Generated by Django 6.0.2 on 2026-02-19 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_verify_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_profile/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='certifications',
            field=models.FileField(blank=True, null=True, upload_to='hr_certifications/'),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='hires_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='hr_profiles/'),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='role',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('manager', 'HR Manager'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hrprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
