# Generated by Django 5.0.6 on 2026-02-19 11:07

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_candidateprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.candidate_profile_image_upload),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.company_logo_upload),
        ),
        migrations.AlterField(
            model_name='hrprofile',
            name='certifications',
            field=models.FileField(blank=True, null=True, upload_to=apps.accounts.models.hr_certification_upload),
        ),
        migrations.AlterField(
            model_name='hrprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.hr_profile_image_upload),
        ),
    ]
