# Generated by Django 5.0.6 on 2026-02-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_company_phone_number_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CANDIDATE', 'Candidate'), ('INTERVIEWER', 'Interviewer'), ('ADMIN', 'Admin'), ('HR', 'HR')], default='CANDIDATE', max_length=20),
        ),
    ]
