# Generated by Django 6.0.2 on 2026-02-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_mfa_enabled_user_mfa_secret_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hr_password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
