# Generated by Django 6.0.2 on 2026-02-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_hrprofile_role_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
