# Generated by Django 5.2.12 on 2026-03-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
