# Generated by Django 5.2.12 on 2026-03-18 06:04

import cloudinary_storage.storage
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_remove_company_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=apps.accounts.models.candidate_profile_image_upload,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=apps.accounts.models.company_logo_upload,
            ),
        ),
        migrations.AlterField(
            model_name="hrprofile",
            name="certifications",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to=apps.accounts.models.hr_certification_upload,
            ),
        ),
        migrations.AlterField(
            model_name="hrprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=apps.accounts.models.hr_profile_image_upload,
            ),
        ),
        migrations.AlterField(
            model_name="hrprofile",
            name="role",
            field=models.CharField(
                choices=[("INTERVIEWER", "INTERVIEWER"), ("HR", "HR")],
                default="HR",
                max_length=20,
            ),
        ),
    ]
