# Generated by Django 5.2.12 on 2026-03-19 06:38

import apps.accounts.models
import utils.cloudinary_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_candidateprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrprofile',
            name='certifications',
            field=models.FileField(blank=True, null=True, storage=utils.cloudinary_storage.PublicRawMediaCloudinaryStorage(), upload_to=apps.accounts.models.hr_certification_upload),
        ),
    ]
