# Generated by Django 6.0.2 on 2026-02-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
