# Generated by Django 5.2.12 on 2026-03-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_is_approve"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="embedd_id",
            field=models.CharField(blank=True, null=True),
        ),
    ]
