# Generated by Django 5.2.12 on 2026-03-14 03:56

import apps.jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_embedd_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=apps.jobs.models.job_application_resume_upload),
        ),
    ]
