# Generated by Django 5.2.12 on 2026-03-18 06:04

import cloudinary_storage.storage
from django.db import migrations, models

import apps.jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_job_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="embedd_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to=apps.jobs.models.job_application_resume_upload,
            ),
        ),
    ]
