# Generated by Django 5.2.12 on 2026-03-19 06:38

from django.db import migrations, models

import apps.jobs.models
import utils.cloudinary_storage


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_savedjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                storage=utils.cloudinary_storage.PublicRawMediaCloudinaryStorage(),
                upload_to=apps.jobs.models.job_application_resume_upload,
            ),
        ),
    ]
