# Generated by Django 5.2.12 on 2026-03-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_jobapplication_reason_jobapplication_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ai_reasoning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='score_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
