# Generated by Django 5.0.6 on 2026-02-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0002_alter_message_options_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_id',
            field=models.PositiveBigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.PositiveBigIntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room_name'], name='live_chat_m_room_na_4ef6f5_idx'),
        ),
    ]
