# Generated by Django 5.0.6 on 2026-02-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0003_message_message_type_message_read_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(blank=True, default='text', max_length=20, null=True),
        ),
    ]
